#!/usr/local/bin/Rscript
t  = read.table("2DN2_A.scores_final.txt")
t2 = read.table("2DN2_A.scores_invitro.txt")
t3 = read.table("2DN2_A.scores_reverse.txt")
png("2DN2_A_Density_Curves.png",width=2500,height=2500,res=300)
plot(density(t2$V1),type="l",xlab="TM-Score",ylab="Density",xlim=c(0,1),main="TM-Score of decoys generated by SAINT2")
points(density(t$V1),type="l",col="blue")
points(density(t3$V1),type="l",col="red")
legend("topright",c("I","C","R"),lty=c(1,1,1),col=c("black","blue","red"))
dev.off()

